version: '3'
services:
  # PHP Service
  core_api:
    build:
      context: .
      dockerfile: 01_API/Dockerfile
    image: core_api
    container_name: core_api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: core_api
      SERVICE_TAGS: dev
      TZ: Asia/Tokyo
    volumes:
      - ./01_API/:/var/www
      - ./01_API/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - /var/www/vendor

  # Nginx Service
  core_server:
    image: nginx:alpine
    container_name: core_server
    restart: unless-stopped
    tty: true
    environment:
      TZ: Asia/Tokyo
    ports:
      - "7019:80"
    volumes:
      - ./01_API/public:/var/www/public
      - ./01_API/nginx/conf.d/:/etc/nginx/conf.d/

  # WEB Vue
  core_web:
    build:
      context: .
      dockerfile: 02_WEB/Dockerfile
    image: core_web
    container_name: core_web
    restart: unless-stopped
    tty: true
    command: npm run dev
    environment:
      CHOKIDAR_USEPOLLING: true
      SERVICE_NAME: core_web
      SERVICE_TAGS: dev
      TZ: Asia/Tokyo
    working_dir: /app
    ports:
      - "7020:7020"
    volumes:
      - ./02_WEB/:/app
      - /app/node_modules
